# Generated by Django 3.2.3 on 2021-05-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(default='UNTITLED', max_length=255),
        ),
    ]
