# Generated by Django 3.2.3 on 2021-05-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
