# Generated by Django 3.2.3 on 2021-05-29 10:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0004_response_is_accepted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='response',
            new_name='Offer',
        ),
    ]
