# Generated by Django 3.2.3 on 2021-06-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_ad_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='ad',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
