# Generated by Django 3.2.3 on 2021-06-06 16:04

import ads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20210606_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[ads.validators.validate_video_format]),
        ),
    ]
